---
- name: Read certificate's contents from remote machine
  ansible.builtin.slurp:
    src: "{{ item }}"
  with_items: "{{ certbot_available_certs_paths }}"
  loop_control:
    # `/fullchain.pem` is the 14
    label: "{{ (item[:-14] | split('/'))[-1] }}"
  register: certbot_certificate_content

- name: Get certificate properties
  community.crypto.x509_certificate_info:
    content: "{{ item.content | b64decode }}"
  loop: "{{ certbot_certificate_content.results }}"
  loop_control:
    # `/fullchain.pem` is the 14
    label: "{{ (item.item[:-14] | split('/'))[-1] }}"
  delegate_to: localhost
  become: false
  register: certbot_crt_info

- name: Build certificate list
  ansible.builtin.set_fact:
    certbot_certs_properties: >-
      {{ lookup('template', 'build-certificate-list.yml.j2') | from_yaml }}
