---
- name: Check variables are correct
  ansible.builtin.import_tasks:
    file: assert.ansible.yml
  run_once: true
  delegate_to: localhost

- name: Configure certbot
  ansible.builtin.include_tasks:
    file: present.ansible.yml
  when: certbot_state == 'present'

- name: Remove certbot
  ansible.builtin.include_tasks:
    file: absent.ansible.yml
  when: certbot_state == 'absent'
